---
#
# Playbook to install the ELK stack + Beats + netdata
- hosts: localhost
  remote_user: ubuntu 
  become: yes
  become_user: root 
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  - { role: metricbeat }
  - { role: ansible-role-netdata }