---
#
# Playbook to install the ELK + netdata
- hosts: localhost
  remote_user: ubuntu 
  become: yes
  become_user: root
  roles:
  - { role: elasticsearch }
  - { role: kibana }
  - { role: metricbeat }
  - { role: filebeat }

